apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: abhishekchauhandev/node-app:e85dc701295b8d70a3bc6bd09f45a620c9270d76
        ports:
        - containerPort: 8080
        