apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: abhishekchauhandev/node-app:f14ecd602b409bbbcdca02c1b1d8f74324657627
        ports:
        - containerPort: 8080
        