apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: abhishekchauhandev/node-app:1a3548e80b3bb5839144e71f415bfc83fd4441c2
        ports:
        - containerPort: 8080
        